# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

import time
from abc import ABC, abstractmethod
from collections import defaultdict
from multiprocessing import Pipe, Process
from os import getcwd
from typing import Callable, Dict, List

from maro.communication.patterns import ManagerEndpoint, SyncWorkerEndpoint
from maro.communication.utils import Signal
from maro.rl.policy import LossInfo, RLPolicy
from maro.rl.types import Trajectory
from maro.rl.utils import MsgTag
from maro.utils import Logger


class AbsPolicyManager(ABC):
    """Facility that controls policy update and serves the latest policy states."""
    def __init__(self):
        super().__init__()

    @abstractmethod
    def update(self, rollout_info: Dict[str, list]):
        """Update policies using roll-out information.

        The roll-out information is grouped by policy name and may be either raw simulation trajectories or loss
        information computed directly by roll-out workers.
        """
        raise NotImplementedError

    @abstractmethod
    def get_state(self):
        """Get the latest policy states."""
        raise NotImplementedError

    @abstractmethod
    def get_version(self):
        """Get the collective policy version."""
        raise NotImplementedError

    def server(
        self,
        group: str,
        num_actors: int,
        max_lag: int = 0,
        endpoint_kwargs: dict = {},
        log_dir: str = getcwd()
    ):
        """Run a server process.

        The process serves the latest policy states to a set of remote actors and receives simulated experiences from
        them.

        Args:
            group (str): Group name for the cluster that includes the server and all actors.
            num_actors (int): Number of remote actors to collect simulation experiences.
            max_lag (int): Maximum policy version lag allowed for experiences collected from remote actors. Experiences
                collected using policy versions older than (current_version - max_lag) will be discarded. Defaults to 0,
                in which case only experiences collected using the latest policy version will be returned.
            endpoint_kwargs: Keyword parameters for the internal ``ManagerEndpoint`` instance. See ``ManagerEndpoint``
                class for details. Defaults to the empty dictionary.
            log_dir (str): Directory to store logs in. Defaults to the current working directory.
        """
        pass


class SimplePolicyManager(AbsPolicyManager):
    """Policy manager that contains all policy instances.

    Args:
        create_policy_func_dict (dict): Dictionary that maps policy names to policy creators. A policy creator is a
            function that takes policy name as the only parameter and return an ``RLPolicy`` instance.
        parallel (bool): If True, the policies will be created in separate processes so that they can be updated in
            parallel. Otherwise, they will be created by the manager itself, in which case they can only be updated
            sequentially. Defaults to False.
        log_dir (str): Directory to store logs in. A ``Logger`` with tag "POLICY_MANAGER" will be created at init
            time and this directory will be used to save the log files generated by it. Defaults to the current
            working directory.
    """
    def __init__(
        self,
        create_policy_func_dict: Dict[str, Callable[[str], RLPolicy]],
        parallel: bool = False,
        log_dir: str = getcwd()
    ):
        super().__init__()
        self._policy_names = list(create_policy_func_dict.keys())
        self._parallel = parallel
        self._logger = Logger("POLICY_MANAGER", dump_folder=log_dir)
        if parallel:
            self._logger.info("Spawning policy host processes")
            self._state_cache = {}
            self._policy_hosts = []
            self._manager_end = {}

            def _policy_host(name, create_policy_func, conn):
                policy = create_policy_func(name)
                conn.send({"type": "init", "policy_state": policy.get_state()})
                while True:
                    msg = conn.recv()
                    if msg["type"] == "learn":
                        info_list = msg["rollout_info"]
                        if isinstance(info_list[0], Trajectory):
                            policy.learn_from_multi_trajectories(info_list)
                        elif isinstance(info_list[0], LossInfo):
                            policy.update_with_multi_loss_info(info_list)
                        else:
                            raise TypeError(
                                f"Roll-out information must be of type 'Trajectory' or 'LossInfo', "
                                f"got {type(info_list[0])}"
                            )
                        conn.send({"type": "learn_done", "policy_state": policy.get_state()})
                    elif msg["type"] == "quit":
                        break

            for name, create_policy_func in create_policy_func_dict.items():
                manager_end, host_end = Pipe()
                self._manager_end[name] = manager_end
                host = Process(target=_policy_host, args=(name, create_policy_func, host_end))
                self._policy_hosts.append(host)
                host.start()

            for policy_name, conn in self._manager_end.items():
                msg = conn.recv()
                if msg["type"] == "init":
                    self._state_cache[policy_name] = msg["policy_state"]
                    self._logger.info(f"Initial state for policy {policy_name} cached")
        else:
            self._logger.info("Creating policy instances locally")
            self._policy_dict = {name: func(name) for name, func in create_policy_func_dict.items()}

        self._version = 0

    def update(self, rollout_info: Dict[str, list]):
        """Update policies using roll-out information.

        The roll-out information is grouped by policy name and may be either raw simulation trajectories or loss
        information computed directly by roll-out workers.
        """
        t0 = time.time()
        if self._parallel:
            for policy_name, info_list in rollout_info.items():
                self._manager_end[policy_name].send({"type": "learn", "rollout_info": info_list})
            for policy_name, conn in self._manager_end.items():
                msg = conn.recv()
                if msg["type"] == "learn_done":
                    self._state_cache[policy_name] = msg["policy_state"]
                    self._logger.info(f"Cached state for policy {policy_name}")
        else:
            for policy_name, info_list in rollout_info.items():
                if not isinstance(info_list, list):
                    info_list = [info_list]
                if isinstance(info_list[0], Trajectory):
                    self._policy_dict[policy_name].learn_from_multi_trajectories(info_list)
                elif isinstance(info_list[0], LossInfo):
                    self._policy_dict[policy_name].update_with_multi_loss_info(info_list)

        self._logger.info(f"Updated policies {list(rollout_info.keys())}")
        self._version += 1
        self._logger.info(f"policy update time: {time.time() - t0}")

    def get_state(self):
        """Get the latest policy states."""
        if self._parallel:
            return self._state_cache
        else:
            return {name: policy.get_state() for name, policy in self._policy_dict.items()}

    def get_version(self):
        """Get the collective policy version."""
        return self._version

    def exit(self):
        """Tell the policy host processes to exit."""
        if self._parallel:
            for conn in self._manager_end.values():
                conn.send({"type": "quit"})


class DistributedPolicyManager(AbsPolicyManager):
    """Policy manager that communicates with a set of remote nodes that house the policy instances.

    Args:
        policy_names (List[str]): Names of the registered policies.
        group (str): Group name for the cluster consisting of the manager and all policy hosts.
        num_hosts (int): Number of hosts. The hosts will be identified by "POLICY_HOST.i", where 0 <= i < num_hosts.
        log_dir (str): Directory to store logs in. A ``Logger`` with tag "POLICY_MANAGER" will be created at init
            time and this directory will be used to save the log files generated by it. Defaults to the current
            working directory.
        endpoint_kwargs: Keyword parameters for the internal ``Proxy`` instance. See ``Proxy`` class
            for details. Defaults to the empty dictionary.
    """
    def __init__(
        self,
        policy_names: List[str],
        group: str,
        num_hosts: int,
        log_dir: str = getcwd(),
        endpoint_kwargs: dict = {}
    ):
        super().__init__()
        self._policy_names = policy_names
        self._endpoint = ManagerEndpoint(group, "POLICY_MANAGER", num_hosts, **endpoint_kwargs)
        self._num_hosts = len(self._endpoint.workers)
        self._logger = Logger("POLICY_MANAGER", dump_folder=log_dir)

        self._policy2host = {}
        self._host2policies = defaultdict(list)

        # assign policies to hosts
        for i, name in enumerate(self._policy_names):
            host_id = i % self._num_hosts
            self._policy2host[name] = f"POLICY_HOST.{host_id}"
            self._host2policies[f"POLICY_HOST.{host_id}"].append(name)

        self._logger.info(f"Policy assignment: {self._policy2host}")

        # ask the hosts to initialize the assigned policies
        for host_id, policy_names in self._host2policies.items():
            self._endpoint.send(host_id, {"type": MsgTag.INIT_POLICIES, "policy_names": policy_names})

        # cache the initial policy states
        self._state_cache, dones = {}, 0
        while True:
            result, _ = self._endpoint.receive()
            for policy_name, policy_state in result["policy_state"].items():
                self._state_cache[policy_name] = policy_state
                self._logger.info(f"Cached state for policy {policy_name}")
            dones += 1
            if dones == self._num_hosts:
                break

        self._version = 0

    def update(self, rollout_info: Dict[str, list]):
        """Update policies using roll-out information.

        The roll-out information is grouped by policy name and may be either raw simulation trajectories or loss
        information computed directly by roll-out workers.
        """
        for host_id, policy_names in self._host2policies.items():
            info_dict = {
                name: rollout_info[name] if isinstance(rollout_info[name], list) else [rollout_info[name]]
                for name in policy_names
            }
            self._endpoint.send(host_id, {"type": MsgTag.LEARN, "rollout_info": info_dict})

        dones = 0
        while True:
            result, _ = self._endpoint.receive()
            for policy_name, policy_state in result["policy_state"].items():
                self._state_cache[policy_name] = policy_state
                self._logger.info(f"Cached state for policy {policy_name}")
            dones += 1
            if dones == self._num_hosts:
                break

        self._version += 1
        self._logger.info(f"Updated policies {list(rollout_info.keys())}")

    def get_state(self):
        """Get the latest policy states."""
        return self._state_cache

    def get_version(self):
        """Get the collective policy version."""
        return self._version

    def exit(self):
        """Tell the remote trainers to exit."""
        for host_id in self._host2policies:
            self._endpoint.send(host_id, {"type": MsgTag.EXIT})
        self._endpoint.close()
        self._logger.info("Exiting...")


def policy_host(
    create_policy_func_dict: Dict[str, Callable[[str], RLPolicy]],
    host_idx: int,
    group: str,
    endpoint_kwargs: dict = {},
    log_dir: str = getcwd()
):
    """Policy host process that can be launched on separate computation nodes.

    Args:
        create_policy_func_dict (dict): A dictionary mapping policy names to functions that create them. The policy
            creation function should have policy name as the only parameter and return an ``RLPolicy`` instance.
        host_idx (int): Integer host index. The host's ID in the cluster will be "POLICY_HOST.{host_idx}".
        group (str): Group name for the training cluster, which includes all policy hosts and a policy manager that
            manages them.
        endpoint_kwargs: Keyword parameters for the internal ``SyncWorkerEndpoint`` instance. See ``SyncWorkerEndpoint``
            class for details. Defaults to the empty dictionary.
        log_dir (str): Directory to store logs in. Defaults to the current working directory.
    """
    policy_dict = {}
    host_id = f"POLICY_HOST.{host_idx}"
    logger = Logger(host_id, dump_folder=log_dir)
    endpoint = SyncWorkerEndpoint(group, host_id, "POLICY_MANAGER", **endpoint_kwargs) 

    while True:
        msg = endpoint.receive()
        if msg == Signal.EXIT:
            endpoint.close()
            logger.info(f"{endpoint.name} exiting...")
            break

        if msg["type"] == MsgTag.INIT_POLICIES:
            for name in msg["policy_names"]:
                policy_dict[name] = create_policy_func_dict[name](name)

            logger.info(f"Initialized policies {msg['policy_names']}")
            endpoint.send({
                "type": MsgTag.INIT_POLICIES_DONE,
                "policy_state": {name: policy.get_state() for name, policy in policy_dict.items()}
            })
        elif msg["type"] == MsgTag.LEARN:
            t0 = time.time()
            for name, info_list in msg["rollout_info"].items():
                if isinstance(info_list[0], Trajectory):
                    logger.info("learning from multiple trajectories")
                    policy_dict[name].learn_from_multi_trajectories(info_list)
                elif isinstance(info_list[0], LossInfo):
                    logger.info("updating with loss info")
                    policy_dict[name].update_with_multi_loss_info(info_list)
                else:
                    raise TypeError(
                        f"Roll-out information must be of type 'Trajectory' or 'LossInfo', got {type(info_list[0])}"
                    )
            logger.debug(f"total policy update time: {time.time() - t0}")
            endpoint.send({
                "type": MsgTag.POLICY_STATE,
                "policy_state": {name: policy_dict[name].get_state() for name in msg["rollout_info"]}
            })
